package ai.dival.dip.modules.tenants;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.Instant;
import java.util.UUID;
import org.springframework.data.domain.Persistable;

/**
 * A customer organisation. The tenant table is the one place a tenant row is not itself
 * tenant-scoped, so it does not extend {@code TenantOwnedEntity}.
 */
@Entity
@Table(name = "tenant")
public class Tenant implements Persistable<UUID> {

    /**
     * Spring Data decides insert-versus-merge from whether the identifier is null. Because this
     * one is assigned, that heuristic would call merge on every save and issue a pointless SELECT
     * before each insert. Tracking newness explicitly avoids it.
     */
    @Transient
    private boolean newRecord = true;

    /**
     * Assigned by the application rather than generated by the database.
     *
     * <p>Provisioning sometimes has to honour an identifier decided elsewhere — a tenant already
     * announced to an identity provider, or one being migrated in — and an assigned key lets that
     * go through the same service and the same validation as any other creation.
     */
    @Id
    private UUID id;

    @Column(name = "name", nullable = false, length = 200)
    private String name;

    /** Stable machine-readable key used in configuration and support tooling. */
    @Column(name = "slug", nullable = false, unique = true, length = 100)
    private String slug;

    @Enumerated(EnumType.STRING)
    @Column(name = "edition", nullable = false, length = 40)
    private Edition edition;

    @Column(name = "default_locale", nullable = false, length = 10)
    private String defaultLocale;

    @Column(name = "active", nullable = false)
    private boolean active;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    protected Tenant() {
        // for JPA
    }

    public Tenant(String name, String slug, Edition edition, String defaultLocale) {
        this(UUID.randomUUID(), name, slug, edition, defaultLocale);
    }

    public Tenant(UUID id, String name, String slug, Edition edition, String defaultLocale) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.edition = edition;
        this.defaultLocale = defaultLocale;
        this.active = true;
        this.createdAt = Instant.now();
    }

    public void deactivate() {
        this.active = false;
    }

    public void activate() {
        this.active = true;
    }

    public void rename(String name) {
        this.name = name;
    }

    public enum Edition {
        BANKING,
        NGO,
        TELECOM,
        GOVERNMENT,
        HEALTHCARE,
        ENTERPRISE
    }

    @Override
    public UUID getId() {
        return id;
    }

    @Override
    public boolean isNew() {
        return newRecord;
    }

    @PostPersist
    @PostLoad
    void markPersisted() {
        this.newRecord = false;
    }

    public String getName() {
        return name;
    }

    public String getSlug() {
        return slug;
    }

    public Edition getEdition() {
        return edition;
    }

    public String getDefaultLocale() {
        return defaultLocale;
    }

    public boolean isActive() {
        return active;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    /** TIX is available to telecom-edition tenants only. */
    public boolean supportsTix() {
        return edition == Edition.TELECOM;
    }
}
