package ai.dival.dip.common.dev;

import ai.dival.dip.modules.tenants.Tenant;
import ai.dival.dip.modules.tenants.TenantRepository;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Profile;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Creates the two demo tenants used by local development.
 *
 * <p>Their IDs are fixed and must match the {@code tenant_id} attributes of the operator users in
 * {@code infra/keycloak/realm-dip.json}: a token carrying a tenant that has no matching row would
 * authenticate happily and then fail on the first write, which is a confusing way to start.
 *
 * <p>Restricted to the {@code local} profile. This never runs in a deployed environment, and it is
 * not a substitute for a migration — seed data that matters belongs in Flyway.
 */
@Component
@Profile("local")
@ConditionalOnProperty(name = "dip.local.seed-tenants", havingValue = "true")
public class LocalTenantSeeder implements ApplicationRunner {

    private static final Logger log = LoggerFactory.getLogger(LocalTenantSeeder.class);

    static final UUID OPERATOR_A = UUID.fromString("11111111-1111-1111-1111-111111111111");
    static final UUID OPERATOR_B = UUID.fromString("22222222-2222-2222-2222-222222222222");

    private final TenantRepository tenants;
    private final JdbcTemplate jdbcTemplate;

    public LocalTenantSeeder(TenantRepository tenants, JdbcTemplate jdbcTemplate) {
        this.tenants = tenants;
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    @Transactional
    public void run(ApplicationArguments args) {
        seed(OPERATOR_A, "Operator A (local)", "operator-a");
        seed(OPERATOR_B, "Operator B (local)", "operator-b");
    }

    private void seed(UUID id, String name, String slug) {
        if (tenants.existsById(id)) {
            return;
        }
        // Inserted directly because the identifier is generated by JPA, and these IDs must be the
        // fixed values the identity provider hands out rather than whatever Hibernate picks.
        jdbcTemplate.update("""
                INSERT INTO tenant (id, name, slug, edition, default_locale, active, created_at)
                VALUES (?, ?, ?, 'TELECOM', 'fr', TRUE, NOW())
                ON CONFLICT (id) DO NOTHING
                """, id, name, slug);
        log.info("Seeded local tenant {} ({})", slug, id);
    }
}
