package ai.dival.dip.modules.files;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Component;

/**
 * Filesystem-backed storage for local development and tests.
 *
 * <p>Selected by {@code dip.files.storage}, defaulting to this one. An S3 implementation declares
 * {@code havingValue = "s3"} and the two never collide.
 *
 * <p>Chosen by property rather than by {@code @ConditionalOnMissingBean}: that annotation is only
 * dependable on auto-configuration classes, where Spring controls the ordering. On a scanned
 * component the evaluation order is undefined, and the bean can silently fail to register.
 */
@Component
@ConditionalOnProperty(name = "dip.files.storage", havingValue = "filesystem", matchIfMissing = true)
public class FilesystemFileStorage implements FileStorage {

    private static final Logger log = LoggerFactory.getLogger(FilesystemFileStorage.class);

    private final Path root;

    public FilesystemFileStorage(@Value("${dip.files.local-root:./build/file-storage}") String root)
            throws IOException {
        this.root = Path.of(root).toAbsolutePath().normalize();
        Files.createDirectories(this.root);
        log.info("File storage using the filesystem at {}", this.root);
    }

    @Override
    public void store(String key, InputStream content, long sizeBytes, String contentType)
            throws IOException {
        Path target = resolve(key);
        Files.createDirectories(target.getParent());
        Files.copy(content, target, StandardCopyOption.REPLACE_EXISTING);
    }

    @Override
    public InputStream read(String key) throws IOException {
        return Files.newInputStream(resolve(key));
    }

    @Override
    public void delete(String key) throws IOException {
        Files.deleteIfExists(resolve(key));
    }

    @Override
    public boolean exists(String key) {
        return Files.exists(resolve(key));
    }

    /**
     * Resolves a key beneath the root, refusing anything that escapes it.
     *
     * <p>Keys are generated by the service and should never contain traversal, but a storage
     * layer that trusts its input is one bug away from writing anywhere on the disk.
     */
    private Path resolve(String key) {
        Path candidate = root.resolve(key).normalize();
        if (!candidate.startsWith(root)) {
            throw new IllegalArgumentException("Storage key escapes the storage root");
        }
        return candidate;
    }
}
